#!/data/data/com.termux/files/usr/bin/bash

import "@/utils/log"
import "@/utils/colors"
import "@/utils/version"
import "@/utils/uninstall"

LOG_FILE="$CORE_CACHE/install_lang.log"
BUN_DATA_DIR="$HOME/.local/share/core-termux-data/bun"
_BUN_INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="${_BUN_INSTALL_DIR}/src"

# ===== PROOT HELPERS =====

_bun_detect_ubuntu_root() {
  local root
  root="$(find /data/data/com.termux -maxdepth 10 -type d \
    -name "rootfs" -path "*/containers/ubuntu/*" 2>/dev/null | head -1)"

  if [ -z "$root" ]; then
    root="$(find /data/data/com.termux -maxdepth 10 -type d \
      -name "ubuntu" -path "*/installed-rootfs/*" 2>/dev/null | head -1)"
  fi

  echo "$root"
}

_bun_proot_ubuntu() {
  proot-distro login \
    --shared-tmp \
    ubuntu \
    -- "$@"
}

# ===== VERSION DETECTION =====

_get_bun_remote_version() {
  _spin_capture "Checking GitHub" curl -fsSL "https://api.github.com/repos/oven-sh/bun/releases/latest" 2>/dev/null |
    grep '"tag_name":' | sed -E 's/.*"bun-v([^"]+)".*/\1/'
}

_get_bun_remote_version_silent() {
  curl -fsSL "https://api.github.com/repos/oven-sh/bun/releases/latest" 2>/dev/null |
    grep '"tag_name":' | sed -E 's/.*"bun-v([^"]+)".*/\1/'
}

# ===== NATIVE INSTALL =====

_install_bun_deps() {
  loading "Installing dependencies" _install_bun_deps_impl
}

_install_bun_deps_impl() {
  local deps=("curl" "unzip" "clang")

  for dep in "${deps[@]}"; do
    if ! command -v "$dep" &>/dev/null; then
      if ! yes | pkg install "$dep" &>>"$LOG_FILE"; then
        log_error "Failed to install $dep"
        return 1
      fi
    fi
  done
  return 0
}

_download_bun_binary() {
  local version="$1"
  local label="$2"
  loading "Downloading Bun v${version} (${label})" _download_bun_binary_impl "$version" "$label"
}

_download_bun_binary_impl() {
  local version="$1"
  local label="$2"

  local zip_name="bun-linux-aarch64"
  if [ "$label" = "android" ]; then
    zip_name="bun-linux-aarch64-android"
  fi

  local url="https://github.com/oven-sh/bun/releases/download/bun-v${version}/${zip_name}.zip"
  local extract_dir="$BUN_DATA_DIR/download/${zip_name}"

  mkdir -p "$BUN_DATA_DIR/download"

  local zip_file="$BUN_DATA_DIR/download/${zip_name}.zip"
  if [ ! -f "${zip_file}" ]; then
    if ! curl -fSL -o "${zip_file}" "${url}" &>>"$LOG_FILE"; then
      log_error "Failed to download Bun binary"
      return 1
    fi
  fi

  if [ ! -f "${extract_dir}/bun" ]; then
    if ! unzip -o "${zip_file}" -d "$BUN_DATA_DIR/download/" &>>"$LOG_FILE"; then
      log_error "Failed to extract Bun binary"
      return 1
    fi
    chmod +x "${extract_dir}/bun"
  fi

  return 0
}

_compile_bun_shim() {
  loading "Compiling bun-android-shim" _compile_bun_shim_impl
}

_compile_bun_shim_impl() {
  local shim_src="${SRC_DIR}/bun-android-shim.c"
  local shim_out="$PREFIX/lib/bun-android-shim.so"

  if [ ! -f "${shim_src}" ]; then
    log_warn "Shim source not found, skipping"
    return 0
  fi

  local cc
  if command -v aarch64-linux-android-gcc &>/dev/null; then
    cc="aarch64-linux-android-gcc"
  elif command -v clang &>/dev/null; then
    cc="clang"
  else
    log_warn "No C compiler found, skipping shim compilation"
    return 0
  fi

  mkdir -p "$PREFIX/lib"

  if ! ${cc} -shared -fPIC -O2 -Wall \
    -o "${shim_out}" \
    "${shim_src}" \
    -ldl &>>"$LOG_FILE"; then
    log_warn "Shim compilation failed"
    return 0
  fi

  return 0
}

_compile_bun_bundle() {
  loading "Compiling bun-bundle" _compile_bun_bundle_impl
}

_compile_bun_bundle_impl() {
  local bundle_src="${SRC_DIR}/bun-bundle.c"
  local bundle_out="$PREFIX/bin/bun-bundle"

  if [ ! -f "${bundle_src}" ]; then
    log_warn "bun-bundle source not found, skipping"
    return 0
  fi

  local cc
  if command -v aarch64-linux-android-gcc &>/dev/null; then
    cc="aarch64-linux-android-gcc"
  elif command -v clang &>/dev/null; then
    cc="clang"
  else
    log_warn "No C compiler found, skipping bun-bundle compilation"
    return 0
  fi

  if ! ${cc} -O2 -Wall \
    -o "${bundle_out}" \
    "${bundle_src}" &>>"$LOG_FILE"; then
    log_warn "bun-bundle compilation failed"
    return 0
  fi

  chmod +x "${bundle_out}"
  return 0
}

_install_bun_binary() {
  loading "Installing bun binary" _install_bun_binary_impl
}

_install_bun_binary_impl() {
  local bin_dir="$PREFIX/bin"
  local lib_dir="$PREFIX/lib"
  local bun_binary="$BUN_DATA_DIR/download/bun-linux-aarch64-android/bun"
  local shim_path="${lib_dir}/bun-android-shim.so"

  mkdir -p "$bin_dir" "$lib_dir"

  cp "${bun_binary}" "${bin_dir}/bun.real"
  chmod 755 "${bin_dir}/bun.real"

  # Generate bash wrapper — more reliable than C on Android/bionic.
  # bash's pwd -P is a shell builtin that resolves physical CWD without
  # calling libc's getcwd(), which is exactly what fails on Android.
  cat > "${bin_dir}/bun" <<-'WRAPPER_EOF'
		#!/data/data/com.termux/files/usr/bin/bash
		# bun wrapper for Termux/Android — generated by core-termux installer

		# LD_PRELOAD shim for dir traversal and standalone binary fix
		export LD_PRELOAD="__BUN_SHIM__"

		# Termux-friendly environment
		export SSL_CERT_FILE="/data/data/com.termux/files/usr/etc/tls/cert.pem"
		export TMPDIR="/data/data/com.termux/files/usr/tmp"
		export HOME="/data/data/com.termux/files/home"
		export BUN_INSTALL_CACHE_DIR="/data/data/com.termux/files/home/.bun/cache"
		export XDG_CACHE_HOME="/data/data/com.termux/files/home/.cache"
		export BUN_MANIFEST_CACHE="/data/data/com.termux/files/home/.cache/bun/manifest"
		export npm_config_cache="/data/data/com.termux/files/home/.npm"
		export BUN_INSTALL_BACKEND="copyfile"

		# Resolve CWD to physical absolute path using shell builtin pwd -P.
		# This bypasses libc's getcwd() which can fail on Android/bionic.
		cd "$(pwd -P 2>/dev/null || pwd)" || true
		export PWD="$(pwd -P 2>/dev/null || pwd)"

		# Detect bunx invocation: bun detects argv[0] for "bunx" mode,
		# but the wrapper breaks this detection. Inject "x" when needed.
		_BUN_CMD="x"
		case "$0" in
			*bunx*) _BUN_CMD="x" ;;
			*)      _BUN_CMD=""   ;;
		esac

		if [ -n "$_BUN_CMD" ]; then
			exec __BUN_REAL__ "$_BUN_CMD" "$@"
		else
			exec __BUN_REAL__ "$@"
		fi
		WRAPPER_EOF

  sed -i "s|__BUN_SHIM__|${shim_path}|g" "${bin_dir}/bun"
  sed -i "s|__BUN_REAL__|${bin_dir}/bun.real|g" "${bin_dir}/bun"
  chmod 755 "${bin_dir}/bun"

  ln -sf "${bin_dir}/bun" "${bin_dir}/bunx"
  return 0
}

_install_bun_native() {
  local version
  version="$(_get_bun_remote_version_silent)"
  if [ -z "$version" ]; then
    log_error "Failed to fetch latest Bun version"
    return 1
  fi

  _install_bun_deps || return 1
  _download_bun_binary "$version" "android" || return 1
  _compile_bun_shim || return 1
  _compile_bun_bundle || return 1
  _install_bun_binary || return 1
  log_success "Bun (native) installed"
  return 0
}

# ===== PROOT-DISTRO INSTALL =====

_install_bun_proot() {
  mkdir -p "$(dirname "$LOG_FILE")"

  local version
  version="$(_get_bun_remote_version_silent)"
  if [ -z "$version" ]; then
    log_error "Failed to fetch latest Bun version"
    return 1
  fi

  _install_bun_proot_impl "$version"
}

_install_bun_proot_impl() {
  local version="$1"

  if ! command -v proot-distro &>/dev/null; then
    loading "Installing proot-distro" _install_bun_proot_deps
  fi

  if [ ! -d "$(_bun_detect_ubuntu_root)" ]; then
    loading "Installing Ubuntu container" _install_bun_proot_ubuntu
  fi

  loading "Installing dependencies in Ubuntu" _install_bun_proot_deps_ubuntu

  local download_url="https://github.com/oven-sh/bun/releases/download/bun-v${version}/bun-linux-aarch64.zip"

  loading "Downloading and installing Bun v${version}" _install_bun_proot_bun "$download_url"

  local ubuntu_root
  ubuntu_root="$(_bun_detect_ubuntu_root)"

  if [ -z "$ubuntu_root" ]; then
    log_error "Ubuntu rootfs not found"
    return 1
  fi

  local bun_bin="$ubuntu_root/usr/local/bin/bun"

  if [ ! -f "$bun_bin" ]; then
    log_error "Bun binary not found after install"
    return 1
  fi

  loading "Creating wrappers" _install_bun_proot_wrappers "$ubuntu_root"

  return 0
}

_install_bun_proot_deps() {
  yes | pkg install proot-distro &>>"$LOG_FILE"
}

_install_bun_proot_ubuntu() {
  proot-distro install ubuntu:24.04 &>>"$LOG_FILE"
}

_install_bun_proot_deps_ubuntu() {
  _bun_proot_ubuntu /bin/bash -c \
    'apt-get update && apt-get upgrade -y && apt-get install -y curl ca-certificates unzip' \
    &>>"$LOG_FILE"
}

_install_bun_proot_bun() {
  local download_url="$1"

  _bun_proot_ubuntu /bin/bash -c "
    export HOME=/root TMPDIR=/tmp
    cd /tmp &&
    curl -fsSL '$download_url' -o bun.zip &&
    unzip -o bun.zip >/dev/null 2>&1 &&
    mkdir -p /usr/local/bin &&
    mv bun-linux-aarch64/bun /usr/local/bin/bun &&
    chmod +x /usr/local/bin/bun &&
    ln -sf /usr/local/bin/bun /usr/local/bin/bunx &&
    rm -rf bun.zip bun-linux-aarch64
  " &>>"$LOG_FILE"
}

_install_bun_proot_wrappers() {
  local ubuntu_root="$1"

  local wrapper_src="$CORE_PATH/tools/lang/bun/bin/bun"
  if [ ! -f "$wrapper_src" ]; then
    log_error "Wrapper template not found at $wrapper_src"
    return 1
  fi
  sed "s|__UBUNTU_ROOTFS__|$ubuntu_root|g" "$wrapper_src" >"$PREFIX/bin/bun"
  chmod +x "$PREFIX/bin/bun"

  local wrapper_bunx_src="$CORE_PATH/tools/lang/bun/bin/bunx"
  if [ -f "$wrapper_bunx_src" ]; then
    sed "s|__UBUNTU_ROOTFS__|$ubuntu_root|g" "$wrapper_bunx_src" >"$PREFIX/bin/bunx"
    chmod +x "$PREFIX/bin/bunx"
  else
    ln -sf "$PREFIX/bin/bun" "$PREFIX/bin/bunx"
  fi
}

# ===== PATH SETUP =====

_bun_setup_path_native() {
  local rc_file=""
  local path_line='export PATH="/data/data/com.termux/files/home/.cache/.bun/bin:$PATH"'

  # Ensure current session can find bun global bins immediately
  case ":$PATH:" in
  *":/data/data/com.termux/files/home/.cache/.bun/bin:"*) ;;
  *) export PATH="/data/data/com.termux/files/home/.cache/.bun/bin:$PATH" ;;
  esac

  # Priority: .zshrc > .bashrc > .bash_profile > .profile (create .bashrc if none)
  if [ -f "$HOME/.zshrc" ]; then
    rc_file="$HOME/.zshrc"
  elif [ -f "$HOME/.bashrc" ]; then
    rc_file="$HOME/.bashrc"
  elif [ -f "$HOME/.bash_profile" ]; then
    rc_file="$HOME/.bash_profile"
  elif [ -f "$HOME/.profile" ]; then
    rc_file="$HOME/.profile"
  else
    rc_file="$HOME/.bashrc"
    touch "$rc_file"
  fi

  # Idempotent: only add if the exact line is not already present
  if grep -qxF "$path_line" "$rc_file" 2>/dev/null; then
    log_info "bun PATH already in $(basename "$rc_file")"
    return 0
  fi

  # Ensure the file ends with a newline before appending
  local last_char
  last_char="$(tail -c 1 "$rc_file" 2>/dev/null || echo "")"
  if [ -n "$last_char" ] && [ "$last_char" != $'\n' ]; then
    echo "" >>"$rc_file"
  fi

  echo "# Added by core-termux bun installer" >>"$rc_file"
  echo "$path_line" >>"$rc_file"
  log_success "Added bun PATH to $(basename "$rc_file")"
}

_bun_setup_path_proot() {
  local ubuntu_root
  ubuntu_root="$(_bun_detect_ubuntu_root)"
  if [ -z "$ubuntu_root" ]; then
    return 0
  fi

  # Inside ubuntu, bun is at /usr/local/bin which is already in PATH.
  # Still add the custom path if user wants it for global bins.
  local rc_file="$ubuntu_root/root/.bashrc"
  local path_line='export PATH="$PATH:/usr/local/bin"'

  if [ -f "$rc_file" ]; then
    if ! grep -qxF "$path_line" "$rc_file" 2>/dev/null; then
      echo "" >>"$rc_file"
      echo "# Added by core-termux bun installer" >>"$rc_file"
      echo "$path_line" >>"$rc_file"
      log_success "Added bun PATH in Ubuntu container (root)"
    fi
  fi
}

# ===== MAIN INSTALL =====

install_bun() {
  if command -v bun &>/dev/null; then
    log_info "Bun is already installed"
    return 2
  fi

  mkdir -p "$(dirname "$LOG_FILE")"

  log_info "Select installation method for Bun:"

  read_select "Installation method" SELECTED_METHOD \
    "Native (recommended) - Android Bionic" \
    "Proot-distro (alternative) - Ubuntu Container"

  case "$SELECTED_METHOD" in
  *Native*)
    _install_bun_native || return 1
    _bun_setup_path_native
    ;;
  *Proot-distro*)
    _install_bun_proot || return 1
    _bun_setup_path_proot
    ;;
  esac

  local installed_version
  installed_version=$(bun --version 2>/dev/null || echo "unknown")
  log_success "Bun v${installed_version} installed successfully"
  return 0
}

# ===== UNINSTALL =====

_uninstall_bun_native_impl() {
  rm -f "$PREFIX/bin/bun" "$PREFIX/bin/bunx" "$PREFIX/bin/bun.real" "$PREFIX/bin/bun-bundle"
  rm -f "$PREFIX/lib/bun-android-shim.so"
  rm -rf "$BUN_DATA_DIR"
}

_uninstall_bun_proot_impl() {
  _bun_proot_ubuntu /bin/bash -c 'rm -f /usr/local/bin/bun' &>>"$LOG_FILE"

  rm -f "$PREFIX/bin/bun" "$PREFIX/bin/bunx"
  return 0
}

_bun_is_native() {
  [ -f "$PREFIX/bin/bun.real" ] || [ -d "$BUN_DATA_DIR/download/bun-linux-aarch64-android" ]
}

_bun_is_proot() {
  local root
  root="$(_bun_detect_ubuntu_root)"
  [ -n "$root" ] && [ -f "$root/usr/local/bin/bun" ]
}

uninstall_bun() {
  mkdir -p "$(dirname "$LOG_FILE")"

  if ! _bun_is_native && ! _bun_is_proot; then
    log_info "Bun is not installed"
    return 2
  fi

  confirm_remove_configs "Bun" \
    "$HOME/.bun" \
    "$HOME/.bunfig.toml" \
    "$HOME/.cache/bun"

  if _bun_is_native; then
    loading "Uninstalling Bun (native)" _uninstall_bun_native_impl
    log_success "Bun (native) uninstalled"
  elif _bun_is_proot; then
    loading "Uninstalling Bun (proot-distro)" _uninstall_bun_proot_impl
    log_success "Bun (proot-distro) uninstalled"
  else
    log_info "Bun is not installed"
    return 2
  fi
  return 0
}

# ===== UPDATE =====

_update_bun_native_impl() {
  rm -f "$PREFIX/bin/bun" "$PREFIX/bin/bunx" "$PREFIX/bin/bun.real" "$PREFIX/bin/bun-bundle"
  rm -f "$PREFIX/lib/bun-android-shim.so"
  rm -rf "$BUN_DATA_DIR/download"
  _install_bun_native
}

_update_bun_proot_impl() {
  local version
  version="$(_get_bun_remote_version_silent)"
  if [ -z "$version" ]; then
    log_error "Failed to fetch latest Bun version"
    return 1
  fi

  local download_url="https://github.com/oven-sh/bun/releases/download/bun-v${version}/bun-linux-aarch64.zip"

  _bun_proot_ubuntu /bin/bash -c 'rm -f /usr/local/bin/bun' &>>"$LOG_FILE"

  _bun_proot_ubuntu /bin/bash -c "
    export HOME=/root TMPDIR=/tmp
    cd /tmp &&
    curl -fsSL '$download_url' -o bun.zip &&
    unzip -o bun.zip >/dev/null 2>&1 &&
    mkdir -p /usr/local/bin &&
    mv bun-linux-aarch64/bun /usr/local/bin/bun &&
    chmod +x /usr/local/bin/bun &&
    rm -rf bun.zip bun-linux-aarch64
  " &>>"$LOG_FILE"

  local ubuntu_root
  ubuntu_root="$(_bun_detect_ubuntu_root)"

  if [ ! -f "$ubuntu_root/usr/local/bin/bun" ]; then
    log_error "Bun binary not found after update"
    return 1
  fi

  log_success "Bun (proot-distro) updated"
  return 0
}

_update_bun_impl() {
  if _bun_is_native; then
    _update_bun_native_impl
    return $?
  fi

  if _bun_is_proot; then
    loading "Updating Bun (proot-distro)" _update_bun_proot_impl
    return $?
  fi

  log_warn "Could not detect Bun installation method"
  return 1
}

update_bun() {
  local installed_ver
  installed_ver="$(_get_installed_version bun)"
  local remote_ver
  remote_ver="$(_get_bun_remote_version)"

  _check_update_needed "Bun" "$installed_ver" "$remote_ver" _update_bun_impl
}

# ===== REINSTALL =====

reinstall_bun() {
  uninstall_bun
  install_bun
}

# ===== AUTO-INSTALL FOR TOOL DEPENDENCIES (non-interactive) =====
# Used by tool installers that depend on bun as a runtime.
# Installs bun natively without any interactive prompt.
_ensure_bun() {
  command -v bun &>/dev/null && return 0

  local _saved_log="${LOG_FILE:-}"
  local _log_dir
  _log_dir="$(dirname "$_saved_log" 2>/dev/null || echo "$CORE_CACHE")"
  local _log="$_log_dir/install_ensure_bun.log"

  LOG_FILE="$_log"
  mkdir -p "$(dirname "$LOG_FILE")" "$CORE_CACHE"

  _install_bun_native || {
    LOG_FILE="$_saved_log"
    return 1
  }
  _bun_setup_path_native

  LOG_FILE="$_saved_log"
  return 0
}

# Also export as a public alias used by CLI tools
install_bun_native_auto() {
  _ensure_bun
}

# ===== PKG FALLBACK — bun → npm =====
# Used by tool installers that depend on bun as a runtime.
# Tries bun first; if bun fails (e.g. "bad system call" on Android),
# falls back to npm automatically.

_ensure_npm() {
  if command -v npm &>/dev/null; then
    return 0
  fi
  log_info "Installing Node.js/npm for fallback package installation..."
  if ! yes | pkg install nodejs-lts &>>"$LOG_FILE"; then
    log_error "Failed to install Node.js/npm"
    return 1
  fi
  return 0
}

# Install a package globally: try bun, fall back to npm on failure.
# Usage: _install_pkg_fallback <package> [extra_flags]
#   extra_flags are passed to BOTH bun and npm (e.g. --ignore-scripts)
_install_pkg_fallback() {
  local pkg="$1"
  local extra_flags="${2:-}"

  # Try bun first (fast path)
  if bun install -g $extra_flags "$pkg" &>>"$LOG_FILE"; then
    return 0
  fi

  log_warn "bun install failed for '${pkg}', falling back to npm..."
  _ensure_npm || return 1

  if npm install -g $extra_flags "$pkg" &>>"$LOG_FILE"; then
    log_info "Installed '${pkg}' via npm (fallback)"
    return 0
  fi

  log_error "Failed to install '${pkg}' via both bun and npm"
  return 1
}

# Uninstall a package globally: try bun, then npm (don't fail).
# Usage: _uninstall_pkg_fallback <package>
_uninstall_pkg_fallback() {
  local pkg="$1"

  # Try bun first
  bun uninstall -g "$pkg" &>>"$LOG_FILE" 2>/dev/null

  # Also try npm (may have been installed via fallback)
  if command -v npm &>/dev/null; then
    npm uninstall -g "$pkg" &>>"$LOG_FILE" 2>/dev/null
  fi

  # Never fail uninstall — package may already be gone
  return 0
}

# Install in a local directory: try bun, fall back to npm.
# Uses bun init / npm init to create a package.json, then installs.
# Usage: _install_pkg_fallback_local <directory> <package>
_install_pkg_fallback_local() {
  local dir="$1"
  local pkg="$2"

  mkdir -p "$dir"

  # Try bun first
  if (cd "$dir" && bun init -y &>>"$LOG_FILE" && bun install "$pkg" &>>"$LOG_FILE"); then
    return 0
  fi

  log_warn "bun install failed for '${pkg}', falling back to npm..."
  _ensure_npm || return 1

  if (cd "$dir" && npm init -y &>>"$LOG_FILE" && npm install "$pkg" &>>"$LOG_FILE"); then
    log_info "Installed '${pkg}' locally via npm (fallback)"
    return 0
  fi

  log_error "Failed to install '${pkg}' locally via both bun and npm"
  return 1
}
